#!/bin/sh
#prerequisites: php55 percona

# УСТАНОВКА zabbix-server-mysql ИЗ РЕПЫ СНОСИТ ПЕРКОНУ
# репы-ключи
echo "deb http://repo.zabbix.com/zabbix/2.2/debian wheezy main" >> /etc/apt/sources.list
wget -O - http://repo.zabbix.com/zabbix-official-repo.key | apt-key add -
apt-get update

#zabbix - prereq
apt-get install nmap libmysqlclient-dev libcurl4-openssl-dev libsnmp-dev


#zabbix-src
wget -O - http://sourceforge.net/projects/zabbix/files/ZABBIX%20Latest%20Stable/2.2.1/zabbix-2.2.1.tar.gz/download > zabbix.tar.gz
tar -zxvf zabbix.tar.gz
cd zabbix*

groupadd zabbix
useradd -g zabbix zabbix

#zabbix-db
echo  "create database zabbix character set utf8;" | mysql
mysql zabbix < database/mysql/schema.sql
# остановитесь здесь, если вы создаете базу данных для Zabbix прокси
mysql zabbix < database/mysql/images.sql
mysql zabbix < database/mysql/data.sql

#КОнфиги
./configure --enable-server --with-mysql --with-net-snmp --with-libcurl

#КОнпеляция
make install

# снова КОнфиги
# прописываем dbPassword TODO sed
nano /usr/local/etc/zabbix_server.conf

#стартуем!
zabbix_server

#zabbix-frontend

sed -i 's/^post_max_size.*/post_max_size = 16M/g' /etc/php5/fpm/php.ini

sed -i 's/^max_execution_time.*/max_execution_time = 300/g' /etc/php5/fpm/php.ini

sed -i 's/^max_input_time.*/max_input_time = 300/g' /etc/php5/fpm/php.ini

sed -i 's/^;date.timezone.*/date.timezone = \"Europe\/Moscow\"/g' /etc/php5/fpm/php.ini

service php5-fpm restart

mkdir -p /var/wwws/zabbix
cd frontends/php
cp -a . /var/wwws/zabbix


wget -O - https://raw.github.com/ivan-antonyuck/debian/master/zabbix/nginx.conf > /etc/nginx/nginx.conf
wget -O - https://raw.github.com/ivan-antonyuck/debian/master/zabbix/zabbix.nginx.conf > /etc/nginx/conf.d/zabbix.nginx.conf